spring:
  profiles:
    include: oauth,real-db
  datasource:
    hikari:
      jdbc-url:
      username:
      password:
      driver-class-name:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  session:
    store-type: jdbc